name: 📝 User Story
description: Granular task within a feature (smaller than a feature, specific implementation)
title: "[Story] "
labels: ["user-story", "task"]
body:
  - type: markdown
    attributes:
      value: |
        ## User Story Template
        Use this for specific, granular tasks that are part of a larger feature.
        Examples: "Create trajectory logging helper function", "Add Zod validation schema for API", "Implement QueryForm component"

  - type: textarea
    id: story-format
    attributes:
      label: User Story
      description: "Format: As a [role], I want [feature], so that [benefit]"
      placeholder: |
        As a developer, I want a reusable trajectory logging helper function, so that I can easily log workflow steps without duplicating code.
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: What must be true for this to be complete? Use checkboxes.
      placeholder: |
        - [ ] Function accepts sessionId, stepName, and async fn as parameters
        - [ ] Logs start time before executing function
        - [ ] Logs end time, latency, and output after execution
        - [ ] Saves record to trajectory_steps table using Drizzle
        - [ ] Handles errors gracefully and logs failure status
        - [ ] Returns original function result unchanged
        - [ ] Type-safe with proper TypeScript generics
        - [ ] Unit tests cover success and error cases
        - [ ] JSDoc comments explain usage
    validations:
      required: true

  - type: textarea
    id: technical-notes
    attributes:
      label: Technical Notes
      description: Implementation hints, constraints, or code snippets
      placeholder: |
        **File:** `src/lib/trajectory/logger.ts`

        **Signature:**
        ```typescript
        async function executeWithLogging<T>(
          sessionId: string,
          stepName: string,
          fn: () => Promise<T>
        ): Promise<T>
        ```

        **Example Usage:**
        ```typescript
        const result = await executeWithLogging(
          sessionId,
          "decomposition",
          async () => {
            const { text } = await generateText({ model: deepseekR1, prompt });
            return { subQueries: parseSubQueries(text) };
          }
        );
        ```

        **Database:**
        - Use Drizzle ORM's `db.insert(trajectorySteps).values(...)`
        - Wrap in try/catch to handle DB errors

  - type: input
    id: related-feature
    attributes:
      label: Related Feature
      description: Link to parent feature using #issue-number
      placeholder: "#11"
    validations:
      required: true

  - type: dropdown
    id: effort
    attributes:
      label: Estimated Effort
      description: T-shirt sizing for this story
      options:
        - XS (< 1 hour)
        - S (1-3 hours)
        - M (3-8 hours)
        - L (1-2 days)
        - XL (2+ days)
    validations:
      required: true

  - type: dropdown
    id: skill-level
    attributes:
      label: Skill Level Required
      description: What level of experience is needed?
      options:
        - Beginner (good first issue)
        - Intermediate (some experience needed)
        - Advanced (requires deep system knowledge)
    validations:
      required: true

  - type: textarea
    id: definition-of-done
    attributes:
      label: Definition of Done
      description: Simple checklist (use checkboxes)
      placeholder: |
        - [ ] Code implemented and working
        - [ ] Unit tests written and passing
        - [ ] Type-safe (no TypeScript errors)
        - [ ] Biome checks pass (bun check)
        - [ ] Code reviewed
        - [ ] Merged to main
